In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset= pd.read_csv('my_bank.csv')

In [3]:
#drops Phone column where it exists
try: 
    dataset=dataset.drop(['Phone'],axis=1)
except:
    pass
dataset

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49.0,91107,4,1.60,1,0,0,1,0,0,0
1,2,200,19,34.0,90089,3,1.50,1,0,0,1,0,0,0
2,3,39,15,11.0,94720,1,NaN,1,0,0,0,0,0,0
3,4,35,9,100.0,94112,1,NaN,2,0,0,0,0,0,0
4,5,35,8,45.0,91330,4,NaN,2,0,0,0,0,0,1
5,6,150,13,29.0,92121,4,0.40,2,155,0,0,0,1,0
6,7,100,27,72.0,91711,2,1.50,2,0,0,0,0,1,0
7,8,50,24,22.0,93943,1,0.30,3,0,0,0,0,0,1
8,9,35,10,NaN,90089,3,0.60,2,104,0,0,0,1,0
9,10,34,9,NaN,93023,1,8.90,3,0,1,0,0,0,0
10,11,65,39,NaN,94710,4,2.40,3,0,0,0,0,0,0
11,12,29,5,NaN,90277,3,0.10,2,0,0,0,0,1,0
12,13,48,23,114.0,93106,2,3.80,3,0,0,1,0,0,0
13,14,59,32,40.0,94920,4,2.50,2,0,0,0,0,1,0
14,15,67,41,112.0,91741,1,2.00,1,0,0,1,0,0,0
15,16,60,30,22.0,95054,1,1.50,3,0,0,0,0,1,1
16,17,38,14,130.0,95010,4,4.70,3,134,1,0,0,0,0
17,18,42,18,81.0,94305,4,2.40,1,0,0,0,0,0,0
18,19,46,21,193.0,91604,2,8.10,3,0,1,0,0,0,0
19,20,55,28,21.0,94720,1,0.50,2,0,0,1,0,0,1
20,21,56,31,25.0,94015,4,0.90,2,111,0,0,0,1,0
21,22,57,27,63.0,90095,3,2.00,3,0,0,0,0,1,0
22,23,29,5,62.0,90277,1,1.20,1,260,0,0,0,1,0
23,24,44,18,43.0,91320,2,0.70,1,163,0,1,0,0,0
24,25,36,11,152.0,95521,2,3.90,1,159,0,0,0,0,1
25,26,43,19,29.0,94305,3,0.50,1,97,0,0,0,1,0
26,27,40,16,83.0,95064,4,0.20,3,0,0,0,0,0,0
27,28,46,20,158.0,90064,1,2.40,1,0,0,0,0,1,1
28,29,56,30,48.0,94539,1,2.20,3,0,0,0,0,1,1
29,30,38,13,119.0,94104,1,3.30,2,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,4976,38,11,29.0,95207,4,1.00,2,0,0,0,0,1,0
4976,4977,29,5,31.0,95039,1,1.80,2,0,0,0,0,1,1
4977,4978,40,15,54.0,90266,3,0.80,3,0,0,0,0,1,0
4978,4979,57,27,63.0,90210,4,2.00,3,0,0,0,0,1,0
4979,4980,50,26,92.0,90740,1,2.60,2,213,0,0,0,0,1
4980,4981,29,5,135.0,95762,3,5.30,1,0,1,0,1,1,1
4981,4982,34,9,195.0,90266,2,3.00,1,122,0,0,0,1,0
4982,4983,36,10,45.0,95126,4,0.20,1,0,0,0,0,0,1
4983,4984,51,26,72.0,95370,1,2.90,1,0,0,0,0,0,0
4984,4985,27,1,98.0,94043,4,2.30,3,0,0,0,0,0,1
4985,4986,48,23,30.0,94720,3,1.70,2,162,0,0,0,1,0
4986,4987,32,6,78.0,95825,1,2.90,3,0,0,0,0,0,0
4987,4988,48,23,43.0,93943,3,1.70,2,159,0,0,0,1,0
4988,4989,34,8,85.0,95134,1,2.50,1,136,0,0,0,0,1
4989,4990,24,0,38.0,93555,1,1.00,3,0,0,0,0,1,0
4990,4991,55,25,58.0,95023,4,2.00,3,219,0,0,0,0,1
4991,4992,51,25,92.0,91330,1,1.90,2,100,0,0,0,0,1
4992,4993,30,5,13.0,90037,4,0.50,3,0,0,0,0,0,0
4993,4994,45,21,218.0,91801,2,6.67,1,0,0,0,0,1,0
4994,4995,64,40,75.0,94588,3,2.00,3,0,0,0,0,1,0
4995,4996,29,3,40.0,92697,1,1.90,3,0,0,0,0,1,0
4996,4997,30,4,15.0,92037,4,0.40,1,85,0,0,0,1,0
4997,4998,63,39,24.0,93023,2,0.30,3,0,0,0,0,0,0
4998,4999,65,40,49.0,90034,3,0.50,2,0,0,0,0,1,0
4999,5000,28,4,83.0,92612,3,0.80,1,0,0,0,0,1,1
5000,5001,56,30,48.0,94539,1,2.20,3,0,0,0,0,1,1
5001,5002,38,13,119.0,94104,1,3.30,2,0,1,0,1,1,1
5002,5003,59,35,35.0,93106,1,1.20,3,122,0,0,0,1,0
5003,5004,40,16,29.0,94117,1,2.00,2,0,0,0,0,1,0
5004,5005,53,28,41.0,94801,2,0.60,3,193,0,0,0,0,0

In [4]:
dataset.fillna(dataset.mean())

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49.000000,91107,4,1.600000,1,0,0,1,0,0,0
1,2,200,19,34.000000,90089,3,1.500000,1,0,0,1,0,0,0
2,3,39,15,11.000000,94720,1,1.938083,1,0,0,0,0,0,0
3,4,35,9,100.000000,94112,1,1.938083,2,0,0,0,0,0,0
4,5,35,8,45.000000,91330,4,1.938083,2,0,0,0,0,0,1
5,6,150,13,29.000000,92121,4,0.400000,2,155,0,0,0,1,0
6,7,100,27,72.000000,91711,2,1.500000,2,0,0,0,0,1,0
7,8,50,24,22.000000,93943,1,0.300000,3,0,0,0,0,0,1
8,9,35,10,73.731654,90089,3,0.600000,2,104,0,0,0,1,0
9,10,34,9,73.731654,93023,1,8.900000,3,0,1,0,0,0,0
10,11,65,39,73.731654,94710,4,2.400000,3,0,0,0,0,0,0
11,12,29,5,73.731654,90277,3,0.100000,2,0,0,0,0,1,0
12,13,48,23,114.000000,93106,2,3.800000,3,0,0,1,0,0,0
13,14,59,32,40.000000,94920,4,2.500000,2,0,0,0,0,1,0
14,15,67,41,112.000000,91741,1,2.000000,1,0,0,1,0,0,0
15,16,60,30,22.000000,95054,1,1.500000,3,0,0,0,0,1,1
16,17,38,14,130.000000,95010,4,4.700000,3,134,1,0,0,0,0
17,18,42,18,81.000000,94305,4,2.400000,1,0,0,0,0,0,0
18,19,46,21,193.000000,91604,2,8.100000,3,0,1,0,0,0,0
19,20,55,28,21.000000,94720,1,0.500000,2,0,0,1,0,0,1
20,21,56,31,25.000000,94015,4,0.900000,2,111,0,0,0,1,0
21,22,57,27,63.000000,90095,3,2.000000,3,0,0,0,0,1,0
22,23,29,5,62.000000,90277,1,1.200000,1,260,0,0,0,1,0
23,24,44,18,43.000000,91320,2,0.700000,1,163,0,1,0,0,0
24,25,36,11,152.000000,95521,2,3.900000,1,159,0,0,0,0,1
25,26,43,19,29.000000,94305,3,0.500000,1,97,0,0,0,1,0
26,27,40,16,83.000000,95064,4,0.200000,3,0,0,0,0,0,0
27,28,46,20,158.000000,90064,1,2.400000,1,0,0,0,0,1,1
28,29,56,30,48.000000,94539,1,2.200000,3,0,0,0,0,1,1
29,30,38,13,119.000000,94104,1,3.300000,2,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,4976,38,11,29.000000,95207,4,1.000000,2,0,0,0,0,1,0
4976,4977,29,5,31.000000,95039,1,1.800000,2,0,0,0,0,1,1
4977,4978,40,15,54.000000,90266,3,0.800000,3,0,0,0,0,1,0
4978,4979,57,27,63.000000,90210,4,2.000000,3,0,0,0,0,1,0
4979,4980,50,26,92.000000,90740,1,2.600000,2,213,0,0,0,0,1
4980,4981,29,5,135.000000,95762,3,5.300000,1,0,1,0,1,1,1
4981,4982,34,9,195.000000,90266,2,3.000000,1,122,0,0,0,1,0
4982,4983,36,10,45.000000,95126,4,0.200000,1,0,0,0,0,0,1
4983,4984,51,26,72.000000,95370,1,2.900000,1,0,0,0,0,0,0
4984,4985,27,1,98.000000,94043,4,2.300000,3,0,0,0,0,0,1
4985,4986,48,23,30.000000,94720,3,1.700000,2,162,0,0,0,1,0
4986,4987,32,6,78.000000,95825,1,2.900000,3,0,0,0,0,0,0
4987,4988,48,23,43.000000,93943,3,1.700000,2,159,0,0,0,1,0
4988,4989,34,8,85.000000,95134,1,2.500000,1,136,0,0,0,0,1
4989,4990,24,0,38.000000,93555,1,1.000000,3,0,0,0,0,1,0
4990,4991,55,25,58.000000,95023,4,2.000000,3,219,0,0,0,0,1
4991,4992,51,25,92.000000,91330,1,1.900000,2,100,0,0,0,0,1
4992,4993,30,5,13.000000,90037,4,0.500000,3,0,0,0,0,0,0
4993,4994,45,21,218.000000,91801,2,6.670000,1,0,0,0,0,1,0
4994,4995,64,40,75.000000,94588,3,2.000000,3,0,0,0,0,1,0
4995,4996,29,3,40.000000,92697,1,1.900000,3,0,0,0,0,1,0
4996,4997,30,4,15.000000,92037,4,0.400000,1,85,0,0,0,1,0
4997,4998,63,39,24.000000,93023,2,0.300000,3,0,0,0,0,0,0
4998,4999,65,40,49.000000,90034,3,0.500000,2,0,0,0,0,1,0
4999,5000,28,4,83.000000,92612,3,0.800000,1,0,0,0,0,1,1
5000,5001,56,30,48.000000,94539,1,2.200000,3,0,0,0,0,1,1
5001,5002,38,13,119.000000,94104,1,3.300000,2,0,1,0,1,1,1
5002,5003,59,35,35.000000,93106,1,1.200000,3,122,0,0,0,1,0
5003,5004,40,16,29.000000,94117,1,2.000000,2,0,0,0,0,1,0
5004,5005,53,28,41.000000,94801,2,0.600000,3,193,0,0,0,0,0